"""
Django settings module for the backend project.
This module contains all configuration settings for the Django application,
including database configuration, installed applications, middleware setup,
static files handling, and CORS settings.
Key Configurations:
- DEBUG: Set to True for development (should be False in production)
- DATABASES: SQLite3 database configuration
- INSTALLED_APPS: Includes Django core apps, DRF, CORS headers, and custom base app
- MIDDLEWARE: Security and session middleware with CORS support
- STATIC_URL: URL prefix for static files
- MEDIA_URL: URL prefix for user-uploaded media files
- CORS_ALLOWED_ORIGINS: Whitelist of allowed cross-origin request sources
Security Notes:
- SECRET_KEY should be kept secret and not committed to version control
- DEBUG should be set to False in production
- ALLOWED_HOSTS should be configured for production deployment
- CORS_ALLOWED_ORIGINS should be restricted to trusted domains only
See: https://docs.djangoproject.com/en/6.0/topics/settings/
Django settings for backend project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(s9)()*_-7ylv_0dh59n21=hfln+c%7hap7j&y4la1ksl2%8up'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Development email settings: print emails to console for password reset testing
if DEBUG:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
    DEFAULT_FROM_EMAIL = 'webmaster@localhost' 


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'base.apps.BaseConfig',
    'corsheaders',

    "rest_framework",
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': False,

    'ALGORITHM': 'HS256',
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',

    'JTI_CLAIM': 'jti',

    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': timedelta(days=1),
}







ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'


# CORS Configuration
# Allow local frontend and admin panel development origins
CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',  # main frontend
    'http://127.0.0.1:3000',
    'http://localhost:3001',  # admin panel dev
    'http://127.0.0.1:3001',
]

# For convenience during local development you can also enable all origins
# WARNING: Do NOT enable this in production
# CORS_ALLOW_ALL_ORIGINS = True

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/


STATIC_URL = 'static/'
MEDIA_URL = '/media/'

STATICFILES_DIRS = [BASE_DIR / 'static',]

MEDIA_ROOT ='static/media'

# ===== PAYMENT GATEWAY CONFIGURATION =====
# Stripe Payment Processing
STRIPE_PUBLIC_KEY = 'pk_test_default'  # Replace with environment variable
STRIPE_SECRET_KEY = 'sk_test_default'   # Replace with environment variable

# PayPal Configuration
PAYPAL_CLIENT_ID = ''  # Configure from environment variables
PAYPAL_SECRET = ''     # Configure from environment variables

# Supported Payment Methods in the application
PAYMENT_METHODS = [
    'PayPal',      # PayPal payment gateway
    'Stripe',      # Stripe card payments  
    'Transfer',    # Bank transfer payment
    'COD',         # Cash on Delivery
]